### ISSUE TITLE
Documentation update missing

### ISSUE THREAD

**Issue by pbek** [bulwarkid/virtual-fido#10]
Thank you for this awesome tool!
It would be great if <https://github.com/bulwarkid/virtual-fido/blob/master/README.md#demo-usage> was updated on how to run it now since <https://github.com/bulwarkid/virtual-fido/commit/a453fd5a92cf5cca62b561b25fdf984ce81d328f>.

**Comment by cmdli** [comment]
Fixed, thanks!

**Comment by pbek** [comment]
Thank you very much!
