### ISSUE TITLE
Running on windows?

### ISSUE THREAD

**Issue by jo-vf** [bulwarkid/virtual-fido#12]
I installed Go Windows and cloned the project today. When running the demo, I am getting the error:

C:\Users\Joachim\Desktop\virtfido\virtual-fido>go run ./cmd/demo start
usbip: error: vhci driver is not loaded
panic: ERROR: Could not read data - read tcp 127.0.0.1:3240->127.0.0.1:57812: wsarecv: An existing connection was forcibly closed by the remote host.

goroutine 6 [running]:
github.com/bulwarkid/virtual-fido/virtual_fido.checkErr(...)
        C:/Users/Joachim/Desktop/virtfido/virtual-fido/virtual_fido/util.go:22
github.com/bulwarkid/virtual-fido/virtual_fido.readBE[...]({0x26ce7fa8158, 0xc00000a078})
        C:/Users/Joachim/Desktop/virtfido/virtual-fido/virtual_fido/util.go:42 +0x159
github.com/bulwarkid/virtual-fido/virtual_fido.(*usbIPServer).handleCommands(0xcddb60?, 0xc000040a50)
        C:/Users/Joachim/Desktop/virtfido/virtual-fido/virtual_fido/usbip_server.go:66 +0x6c
github.com/bulwarkid/virtual-fido/virtual_fido.(*usbIPServer).handleConnection(0xc000008e70, 0xc000040a50)
        C:/Users/Joachim/Desktop/virtfido/virtual-fido/virtual_fido/usbip_server.go:58 +0x33a
github.com/bulwarkid/virtual-fido/virtual_fido.(*usbIPServer).start(0xc09380?)
        C:/Users/Joachim/Desktop/virtfido/virtual-fido/virtual_fido/usbip_server.go:37 +0x138
github.com/bulwarkid/virtual-fido/virtual_fido.Start({0xce12e0?, 0xc00004c240})
        C:/Users/Joachim/Desktop/virtfido/virtual-fido/virtual_fido/virtual_fido.go:9 +0x365
main.runServer.func1()
        C:/Users/Joachim/Desktop/virtfido/virtual-fido/cmd/demo/server.go:77 +0x2a
created by main.runServer
        C:/Users/Joachim/Desktop/virtfido/virtual-fido/cmd/demo/server.go:76 +0xa5
exit status 2

what am I doing wrong?
Thanks, Joachim

**Comment by richardbiely** [comment]
I believe you have to install the usbip driver first.

From your usbip folder run:
usbip install -w

**Comment by jo-vf** [comment]
that got me past the initial issue. For other stumbling about the same, one can uninstall usbip with `usbip uninstall -w`.

**Comment by alexeygritsenko** [comment]
Thanks for the tip. If my experience is useful to someone, the driver was not installed for me. I took the more recent version from here https://github.com/cezanne/usbip-win/releases and it installed.
