### ISSUE TITLE
./client_usbip.go:16:15: undefined usbip.NewUSBDevice

### ISSUE THREAD

**Issue by CavoCode** [bulwarkid/virtual-fido#34]
This error appears when trying to run your project. I have installed go and looked into the code to find that there is no function named NewUSBDevice in usbip? But there is in the usb folder files. 

Please help? Why does this not work out-of-the-box, is there something I am missing other than installing Go?

**Comment by cmdli** [comment]
My apologies; I was doing some development on MacOS but this seems to have broken Linux/Windows. I fixed the issue in https://github.com/bulwarkid/virtual-fido/commit/9ad6e59a6a8435f27cd3aadbe2aa0626ac211f5c. Could you pull and see if this fixed the issue?

**Comment by CavoCode** [comment]
Issue is now fixed, though now I am getting vhci driver is not loaded error.

**Comment by CavoCode** [comment]
Fixed that too. Thank you for the help, I really appreciate the assistance and project :)
